[package]
org = "ballerinai"
name = "observe"
version = "@toml.version@"
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
path = "../native/build/libs/observe-internal-native-@project.version@.jar"
