[package]
org = "ballerinai"
name = "observe"
version = "1.1.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
path = "../native/build/libs/observe-internal-native-1.1.0-SNAPSHOT.jar"
